language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests and run 
before_script:
  - echo "no tests now."

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  # - docker build -t reverseproxy ./reverseproxy

  #tagging
  - docker tag udagram-frontend faavour/udagram-frontend:v1
  - docker tag udagram-api-user faavour/udagram-api-user:v1
  - docker tag udagram-api-feed faavour/udagram-api-feed:v1
  # - docker tag reverseproxy faavour/reverseproxy:v1


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push faavour/udagram-frontend:v1
  - docker push faavour/udagram-api-user:v1
  - docker push faavour/udagram-api-feed:v1
  # - docker push faavour/reverseproxy:v1